canonifyurls = true
paginate = 10
theme="startbootstrap-clean-blog"
baseurl = "your site url"
languagecode = "en-us"
title = "The Rod Serling Memorial Foundation"
copyright = "© 2015 rsmf"

[author]
  name = "The Rod Serling Memorial Foundation"

[params]
  DateForm = "Jan 2, 2006"
  Description = "I Describe the RSMF"
  Author = "RSMF"
  email = "rod@rodserling.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/humboldtux"
[[params.social]]
  title = "github"
  url = "https://github.com/humboldtux"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180

