theme="material-design"
baseurl = "Your Site URL"
languageCode = "en-us"
title = "The Rod Serling Memorial Foundation"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 RSMF"

[params]
  description = "Your Site Description" # optional
  twitter = "Your Twitter Name" # optional
  headerCover = "images/headerCover.png" # optional
  footerCover = "images/footerCover.png" # optional
#  github = "Your Github Name" # optional
#  facebook = "Your facebook Name" # optional
#  gplus = "Your Google+ profile name" # optional
#  linkedin = "Your LinkedIn Name" # optional
#  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
