canonifyurls = true
paginate = 10
theme="startbootstrap-clean-blog"
baseurl = "localhost"
languagecode = "en-us"
title = "The Rod Serling Memorial Foundation"
copyright = "© 2016 Rod Serling Memorial Foundation"

[author]
  name = "The Rod Serling Memorial Foundation"

[params]
  DateForm = "Jan 2, 2006"
  Description = "Binghamton, New York"
  Author = "RSMF"
  email = "rod@rodserling.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/rodserlingfoundation"
[[params.social]]
  title = "github"
  url = "https://github.com/humboldtux"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/whoweare"
  weight = -140
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = -120

