wordpress:
  image: wordpress
  links: 
    - wordpress_db:mysql
  ports:
    - 8080:80
  environment:
    WORDPRESS_DB_PASSWORD: rodserling
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: rodserling
